---
title: 'Spatial Scaling of SAD: Update'
author: "A. J. Rominger"
date: "6/4/2017"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Re-working some results

For a few of the forest plots I have, I've re-evaluate the scaling of SADs using some new methods.  The below analysis still uses the $z^2$ values that we discussed long ago.  To jog your memory, $z^2$ is a description of goodness of fit derived from the liklihood of the data given the model of interest.  In this case the model of interest is Fisher's log-series because we'd like to evaluate whether small scales conform to the log-series while large scales deviate from it.  The standardization occurs as such:
$$
z^2 = \left(\frac{\text{logLik}(x \mid model) - E[\text{logLik}(logLik(x_0 \mid model))]}{\sqrt{Var[\text{logLik}(logLik(x_0 \mid model))]}}\right)^2
$$
where $x$ is the observed data and $x_0$ is a hypothetical data set conforming perfectly to the model.  Thus $z^2$ measures the likelihood of the observed data relative to the likelihood of a hypothetical data set generated by the model itself.

This measure is thus "standardized," but unfortunately because of the Central Limit Theorum, it is sensitive to sample size (i.e. the number of species in the sample).  Thus if we calculate $z^2$ from small sub plots to the entire plot, we expect it to increase across this range regardless of what the true underlying SAD is. We can get around this issue by comparing a spatial subset of the plot with a random subset of the plot of the same sample size.  In Figure XX I do that.

What we see in Figure XX is that for all plots at small scale both spatial and random subsets of the data match the log-series prediction (i.e. have small $z^2$ values).  As we increase scale both spatial and random subsets deviate from the log-series.  I expected the random subsets to look more like the large scale, while the spatial subset transitioned from conforming to log-series and then deviating from it at larger scale.  I'm currently stumped as to why spatial and random subsets would follow the same pattern across scales.